"""empty message

Revision ID: 3270f2ca3758
Revises: f72d38a9e3e3
Create Date: 2018-05-01 10:17:07.692688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3270f2ca3758'
down_revision = 'f72d38a9e3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('desktops', sa.Column('system', sa.String(length=50), server_default='', nullable=True))
    op.add_column('desktops', sa.Column('user', sa.String(length=50), server_default='', nullable=True))
    op.create_unique_constraint(None, 'desktops', ['id'])
    op.create_unique_constraint(None, 'messages', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'user_desktops', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_desktops', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'messages', type_='unique')
    op.drop_constraint(None, 'desktops', type_='unique')
    op.drop_column('desktops', 'user')
    op.drop_column('desktops', 'system')
    # ### end Alembic commands ###
