"""empty message

Revision ID: 6683f9dea9fd
Revises: 3270f2ca3758
Create Date: 2018-05-01 10:20:17.889311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6683f9dea9fd'
down_revision = '3270f2ca3758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('desktops', sa.Column('server_password', sa.String(length=50), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('desktops', 'server_password')
    # ### end Alembic commands ###
