"""empty message

Revision ID: d1628bbde268
Revises: 6683f9dea9fd
Create Date: 2018-05-07 16:19:32.662176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1628bbde268'
down_revision = '6683f9dea9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user', sa.String(length=50), server_default='', nullable=True),
    sa.Column('operate', sa.String(length=100), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_logs_create_time'), 'logs', ['create_time'], unique=False)
    op.create_index(op.f('ix_logs_update_time'), 'logs', ['update_time'], unique=False)
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('create_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='messages_pkey'),
    sa.UniqueConstraint('id', name='messages_id_key')
    )
    op.drop_index(op.f('ix_logs_update_time'), table_name='logs')
    op.drop_index(op.f('ix_logs_create_time'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
