"""empty message

Revision ID: f72d38a9e3e3
Revises: 
Create Date: 2018-04-30 12:38:44.475794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72d38a9e3e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desktops',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=50), server_default='', nullable=True),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('server', sa.String(length=50), server_default='', nullable=True),
    sa.Column('port', sa.String(length=50), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_desktops_create_time'), 'desktops', ['create_time'], unique=False)
    op.create_index(op.f('ix_desktops_update_time'), 'desktops', ['update_time'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('message', sa.Text(), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_messages_create_time'), 'messages', ['create_time'], unique=False)
    op.create_index(op.f('ix_messages_update_time'), 'messages', ['update_time'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=50), server_default='', nullable=True),
    sa.Column('description', sa.String(length=100), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_roles_create_time'), 'roles', ['create_time'], unique=False)
    op.create_index(op.f('ix_roles_update_time'), 'roles', ['update_time'], unique=False)
    op.create_table('user_desktops',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), server_default='0', nullable=True),
    sa.Column('desktop_id', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_desktops_create_time'), 'user_desktops', ['create_time'], unique=False)
    op.create_index(op.f('ix_user_desktops_update_time'), 'user_desktops', ['update_time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(length=50), server_default='', nullable=True),
    sa.Column('email', sa.String(length=100), server_default='', nullable=True),
    sa.Column('role_id', sa.Integer(), server_default='0', nullable=True),
    sa.Column('active', sa.Integer(), server_default='0', nullable=True),
    sa.Column('password', sa.String(length=100), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_create_time'), 'users', ['create_time'], unique=False)
    op.create_index(op.f('ix_users_update_time'), 'users', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_update_time'), table_name='users')
    op.drop_index(op.f('ix_users_create_time'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_desktops_update_time'), table_name='user_desktops')
    op.drop_index(op.f('ix_user_desktops_create_time'), table_name='user_desktops')
    op.drop_table('user_desktops')
    op.drop_index(op.f('ix_roles_update_time'), table_name='roles')
    op.drop_index(op.f('ix_roles_create_time'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_messages_update_time'), table_name='messages')
    op.drop_index(op.f('ix_messages_create_time'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_desktops_update_time'), table_name='desktops')
    op.drop_index(op.f('ix_desktops_create_time'), table_name='desktops')
    op.drop_table('desktops')
    # ### end Alembic commands ###
